<?php
/**
 * This file was automatically generated by the PHPSTYLE plugin
 * to change style settings, modify the phpstyle.neon file.
 * https://github.com/jspaetzel/phpstyle
 */
use PHPStyle\PHPStyle;

require_once __DIR__ . '/vendor/autoload.php';

return (new PHPStyle())->getConfig('phpstyle.neon');

