#!/bin/bash
# Downloads php-cs-fixer if needed, loads phpstyle.neon, and runs the fixer.

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

FIXER_BIN="$PWD/vendor/bin/php-cs-fixer"
if [ ! -f $FIXER_BIN ]; then
  echo "Downloading php-cs-fixer"
  wget https://cs.symfony.com/download/php-cs-fixer-v3.phar -O $FIXER_BIN
  chmod +x $FIXER_BIN
fi

STYLE_NEON="$PWD/phpstyle.neon"
if [ ! -f "$STYLE_NEON" ]; then
  STYLE_NEON="$SCRIPT_DIR/phpstyle.neon"
fi

echo "Using PHPStyle config: $STYLE_NEON"
echo
echo "Running Fixer"
echo

$FIXER_BIN fix --config="$SCRIPT_DIR/.php-cs-fixer.dist.php"

